# Generated by Django 3.2.8 on 2021-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_alter_postmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='S',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Type',
            field=models.CharField(choices=[('բնակարան', 'բնակարան'), ('առանձնատուն', 'առանձնատւն')], default='____________', max_length=15),
        ),
    ]
